micronaut:
  application:
    name: customer
datasources:
  default:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: qwe
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate:
  hbm2ddl.auto: validate
  show_sql: true
flyway:
  datasources:
    default:
      enabled: true
