name: Deploy Micronaut to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: temurin
        cache: 'gradle'
        cache-dependency-path: | # optional
          sub-project/*.gradle*
          sub-project/**/gradle-wrapper.properties
      
    - name: Build Micronaut application
      run: ./gradlew build --no-daemon

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/resources/main  # Adjust if necessary
        publish_branch: gh-pages
